# Generated by Django 5.1.5 on 2025-02-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_membershipplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.TextField(default='Default description'),
        ),
    ]
